### ISSUE TITLE
"Peculiar error" trying to capture asterisk

### ISSUE THREAD

**Issue by priyadarshan** [joddie/pcre2el#16]
Trying to capture one or more asterisks, like `** test` I though of using the legit PCRE `(\*+)`, but trying this:
`(rxt-pcre-to-elisp "(\*+)")`
throws:
`rxt-error: peculiar error: "Unrecognized PCRE extended construction (*+)"`
while this works:
`(rxt-pcre-to-elisp "(\\*+)")`

Is that a limitation? I could not find it listed in the README file.

Thank you for `pcre2el`!

**Comment by joddie** [comment]
If you want to represent the sequence of characters `(\*+)` in an Elisp string, you need to double the backslash: `"(\\*+)"`.  If you write `"(\*+)"`, that represents `(*+)`, which looks like one of the PCRE backtracking control verbs `(*FAIL)` (which are unsupported and can't be supported, hence the error message).

However, it's not good that this gives the "peculiar error" message -- that probably means that `rxt-error` is not getting declared properly as a condition symbol, so thank you for the bug report.  What version of Emacs is this on, BTW?

**Comment by priyadarshan** [comment]
Thank you, I probably misunderstood the process then.

I knew what you said was the case for interactive `pcre2el` functions, but I thought that the "programmatic" function `rxt-pcre-to-elisp` was taking (almost) any legit PCRE expression and returning its corresponding legit elisp regex?

Some regex tools seems to accept `(\*+) as a legit PCRE, like: http://www.regextester.com/?fam=1939 but I am not at all a regex expert.

I was keen to be able to programmatically use (almost) any PCRE expressions, so that they could be shared with any other languages/tools, without worrying to fix Emacs idiosyncrasies.

The Emacs I tried that on is `GNU Emacs 24.4.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2014-10-21 on builder10-9.porkrind.org`

Thank you!

**Comment by joddie** [comment]
Hi,

> I knew what you said was the case for interactive pcre2el functions, but I thought that the "programmatic" function rxt-pcre-to-elisp was taking (almost) any legit PCRE expression and returning its corresponding legit elisp regex?

Yes, that's what it does, but if used in an Elisp program, you still need to write the argument as a string constant, which requires escaping backslashes and double quotes.  In other words, the five-character string `(\*+)` has to be represented in an Elisp program as `"(\\*+)"`.  The "extra" backslash is a function of how the Elisp reader works, which is outside the control of Elisp programs.  This is the same in, e.g., Python, where you have to either write `"(\\*+)"` or use a raw-string, `r"(\*+)"`.  People have proposed adding raw strings and/or Common Lisp-style reader macros to Elisp before, but those proposals have been rejected, I think because they make the syntax less regular and structured editing more difficult to implement. (I think this is probably the right decision on the Emacs maintainers' part, FWIW).

> Some regex tools seems to accept (\*+) as a legit PCRE, like: http://www.regextester.com/?fam=1939 but I am not at all a regex expert.

I think it is legit: it represents a single subgroup, containing one or more `*` characters.  This is also what `M-x rxt-explain-pcre RET (\*+) RET` displays: `(submatch (one-or-more "*"))`.  So I think it is handled correctly.

I haven't been able to track down the other problem you mention (`peculiar error`), so will leave this open for now.

**Comment by priyadarshan** [comment]
Thank you for taking the time to explaing in detail. Very instructive for me. Thanks.

**Comment by joddie** [comment]
You are very welcome!
