### ISSUE TITLE
pcre-mode and evil-search

### ISSUE THREAD

**Issue by nugend** [joddie/pcre2el#19]
Hi, not sure if this is the right place to ask this:

Is there a way to get the pcre-mode working with evil-search's evil-search-previous and evil-search-next commands? evil-search-forward and evil-search-backward seem to play nice with the isearch module, but when you use either the search previous or search next it seems to go back to using the non-pcre regex search.

I'm testing this on the latest version of spacemacs with the pcre2el layer enabled, if that helps. (or maybe I should bug spacemacs about this? or evil-search?)

**Comment by joddie** [comment]
Hi, thanks for the report.  I think this is probably the right place to ask this.

I don't use evil-mode or spacemacs so I'm not sure what the issue is, but I'll look into it. I should have some time closer to the end of next week.

Since I barely remember how vi-style keybindings work, can you provide a simple recipe to reproduce, starting with installing evil-mode or spacemacs?

**Comment by nugend** [comment]
Okay, starting from having spacemacs installed (and select vi mode at the startup of spacemacs):

Open ~/.spacemacs.
Add 'pcre2el' to dotspacemacs-configuration-layers (no quotes)
Restart emacs (you can open any file you like or ~/.spacemacs again)
Enable pcre-mode by typing <Spc>-: pcre-mode
Use the '/' key to start a regexp search.
Type a regex, such as dotspacemacs-(configuration|additional|excluded)
Hit enter
Note that it jumps to the first occurrence.
Hit the 'n' key to attempt to jump forward or the 'N' key to attempt to jump backwards. It should fail

Turn off pcre-mode (simplest way is just restarting emacs)
Type a regex with the backslash syntax.
Hit enter
Note that it jumps to the first occurrence.
Hit the 'n' key to jump forward or the 'N' key to jump backwards. It works fine (for me anyhow!)

**Comment by joddie** [comment]
Think I may have a fix for this (only lightly tested). Can you try the version in the `fix/evil-search` branch and see if it fixes the problem without causing other issues?

**Comment by nugend** [comment]
Maybe I installed the fix incorrectly (just patched the pcre2el.el file in the directory containing it), but it doesn't seem to have changed the behavior at all.

**Comment by joddie** [comment]
Hmm. Does the revised patch change anything?  There are some tricky issues with advice and the order in which files are loaded.

Applying the patch that way should work, provided you also `M-x byte-compile-file` again (and test in a fresh Emacs instance, ideally; otherwise, do `M-x emacs-lisp-byte-compile-and-load`).

If it still doesn't work, does toggling `pcre-mode` off and on again change anything?

**Comment by nugend** [comment]
Seems to be working in latest Spacemacs. Thanks for fixing it!

**Comment by Silex** [comment]
Hum I just switched to evil and suffer from this. I'll try to test a bit what the issue is and if your branch fixes it.
