### ISSUE TITLE
rx form with two question marks

### ISSUE THREAD

**Issue by jiyoo** [joddie/pcre2el#3]
If I place cursor at the following non-greedy zero-or-more type of elisp regexp

    "a??"

and type `C-c / x` to get an rx form, what I get is

    (\?\? "a")

But if I use that as an rx form, what I get back is a greedy version:

    (rx (\?\? "a")) ; ⇒ "a?"

The docstring of `rx` doesn't say question marks should be escaped. Maybe pcre2el should be changed to return `(?? "a")` rather than `(\?\? "a")`. But then it's a bit awkward to return `(?? "a")` because that's the same as `(63 "a")` so it's not pretty when printed. Not sure how this issue is to be resolved.

Some experiments:

    ;; how rx macro treats question marks
    (list (rx (? "a"))
          (rx (\? "a"))
          (rx (?? "a"))
          (rx (\?? "a"))
          (rx (\?\? "a")))
    ⇒ ("a?" "a?" "a??" "a?" "a?")
    
    ;; how elisp reader reads question marks
    (list (quote (? "a"))
          (quote (\? "a"))
          (quote (?? "a"))
          (quote (\?? "a"))
          (quote (\?\? "a")))
    ⇒ ((32 "a") (\? "a") (63 "a") (\?\? "a") (\?\? "a"))

**Comment by joddie** [comment]
This should now be fixed in master.  Thank you for the report.  I did not understand before that `rx` uses the character notations `? ` (space) and `??` (question mark), not the symbols `\?` and `\?\?`.  `rxt-adt->rx` now generates forms with the correct characters, and `rxt-print-rx` should print them correctly.

**Comment by priyadarshan** [comment]
Thanks, this is nice!
